name: Compile

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    # Ref: https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: xfangfang/gcc-4.7-arm-linux-gnueabi:latest
            options: -v ${{ github.workspace }}:/src
            run: |
                cd /src && tar -zxvf lib.tar.gz && mv usr/lib lib
                cd /src/task
                ./configure --enable-gtk2 --host=arm-linux-gnueabi --with-shared --prefix=/src/dist
                echo "LDFLAGS =  -L/usr/arm-linux-gnueabi/lib -L/src/lib" >> config.mk
                echo "GTK_LIBS =  -lgtk-x11-2.0 -lgdk-x11-2.0 -lXrender -lXinerama -lXext -lgdk_pixbuf-2.0 -lpangocairo-1.0 -lXdamage -lXfixes -latk-1.0 -lcairo -lpixman-1 -lpng16 -lxcb-shm -lxcb-render -lX11 -lxcb -lXau -lXdmcp -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lz -lexpat -lgobject-2.0 -lffi -lgmodule-2.0 -lgthread-2.0 -lglib-2.0 -lstdc++" >> config.mk
                make clean && make -j
                cd /src
                zip -r dist.zip dist
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: dist.zip
            path: ${{ github.workspace }}/dist.zip